backend:
  name: github
  repo: GeneseeValleyCalligraphyGuild/gvcalligraphy.org

media_folder: public/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "Pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    extension: md
    format: frontmatter
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "general-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
